# Generated by Django 4.1.5 on 2023-01-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_storage", models.IntegerField()),
                ("max_storage", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
